### ISSUE TITLE
Cant install addon on firefox  android

### ISSUE THREAD

**Issue by oldman20** [anime-vsub/app#75]
As u can see i cant install addon on firefox mobile, how can i solve it? Thank
![Screenshot_20230708-133623_Firefox Nightly](https://github.com/anime-vsub/app/assets/39668756/e603c5a0-01aa-4105-bb4c-1198d32bdd66)
![Screenshot_20230708-133614_Firefox Nightly](https://github.com/anime-vsub/app/assets/39668756/93a82292-1475-4d83-b1d2-7f8814a9cb40)

**Comment by tachibana-shin** [comment]
use the file `mv2-extension` if you use Firefox

ideally use the Flow browser

**Comment by tachibana-shin** [comment]
we are working on trying to publish it to FireFox Addons Android but that seems difficult due to the mv3-mv2 migration

**Comment by oldman20** [comment]
> 

where can i get that file?

**Comment by tachibana-shin** [comment]
You can find them here: https://github.com/anime-vsub/extension-animevsub-helper/releases/tag/v1.0.15

If you use Flow Browser you can directly access the Microsoft Edge Store and install the add-on instantly.

**Comment by oldman20** [comment]
> You can find them here: https://github.com/anime-vsub/extension-animevsub-helper/releases/tag/v1.0.15
> 
> If you use Flow Browser you can directly access the Microsoft Edge Store and install the add-on instantly.

thank but i downloaded and can find the way to install mv2-extension.xpi or mv2-extension.zip on Firefox nightly android
