### ISSUE TITLE
Please make file IPA for IOS

### ISSUE THREAD

**Issue by ThanhPhuoc91** [anime-vsub/app#90]
Make ipa for ios please.

**Comment by tachibana-shin** [comment]
Why do you recommend this?

**Comment by tachibana-shin** [comment]
> > Why do you recommend this?
> 
> Can you help me install this app to my iphone? Thanks

Apple does not allow us to do so. If you want to install it you have to pay apple or you have to jailbreak your device

**Comment by ThanhPhuoc91** [comment]
> > > Why do you recommend this?
> > 
> > 
> > Can you help me install this app to my iphone? Thanks
> 
> Apple does not allow us to do so. If you want to install it you have to pay apple or you have to jailbreak your device

Can you share me IPA file ? I can install with trollstore. Please

**Comment by tachibana-shin** [comment]
> > > > Why do you recommend this?
> > > 
> > > 
> > > Can you help me install this app to my iphone? Thanks
> > 
> > 
> > Apple does not allow us to do so. If you want to install it you have to pay apple or you have to jailbreak your device
> 
> Can you share me IPA file ? I can install with trollstore. Please

If you have a Mac you can compile this project yourself. It already has the code to run on iOS, you just need to download it and compile

**Comment by ThanhPhuoc91** [comment]
Im not a developer but i will try it. Thanks for you support. :))

**Comment by ThanhPhuoc91** [comment]
Can i ask one last question? Are you Vietnamese?

**Comment by tachibana-shin** [comment]
> Can i ask one last question? Are you Vietnamese?

The original project creator is Vietnamese and I am just the maintainer

**Comment by ThanhPhuoc91** [comment]
Oh thanks

**Comment by tachibana-shin** [comment]
Done. App for iOS full supported with `bun build:ios`
